name: pdf-converter-services
services:
  gateway:
    image: ghcr.io/crunchydeer30/pdf-gateway:0.1.0
    build:
      context: "./0. gateway"
      dockerfile: Dockerfile
    env_file:
      - ./.env

  converter-service:
    image: ghcr.io/crunchydeer30/pdf-converter-service:0.1.0
    build:
      context: "./1. converter-service"
      dockerfile: Dockerfile
    env_file:
      - ./.env

  converter-worker:
    image: ghcr.io/crunchydeer30/pdf-converter-worker:0.1.0
    build:
      context: "./2. converter-worker"
      dockerfile: Dockerfile
    env_file:
      - ./.env

  cron-service:
    image: ghcr.io/crunchydeer30/pdf-cron-service:0.1.0
    build:
      context: "./3. cron-service"
      dockerfile: Dockerfile
    env_file:
      - ./.env

  client:
    image: ghcr.io/crunchydeer30/pdf-client:0.1.0
    build:
      context: "./client"
      dockerfile: Dockerfile
    env_file:
      - ./.env