services:
  rabbitmq:
    image: rabbitmq:management-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 2s
      retries: 5
    env_file:
      - ./.env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./docker-volumes/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker-volumes/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./docker-volumes/redis/cache:/data
