name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: gateway:build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:0. gateway"
          tags: ghcr.io/crunchydeer30/pdf-gateway:0.1.0

      - name: converter-service:build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:1. converter-service"
          tags: ghcr.io/crunchydeer30/pdf-converter-service:0.1.0

      - name: converter-worker:build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:2. converter-worker"
          tags: ghcr.io/crunchydeer30/pdf-converter-worker:0.1.0

      - name: cron-service:build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:3. cron-service"
          tags: ghcr.io/crunchydeer30/pdf-cron-service:0.1.0

      - name: client:build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:client"
          tags: ghcr.io/crunchydeer30/pdf-client:0.1.0
          secret-envs:
            - NEXT_PUBLIC_API_GATEWAY=${{ secrets.NEXT_PUBLIC_API_GATEWAY }}