on:
  push:
    paths-ignore:
      - "*"
      - "!0. gateway/**"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        working-directory: "0. gateway"
        run: pnpm install

      - name: Lint
        working-directory: "0. gateway"
        run: pnpm lint
